/**
 * SVGs for elements are generated by the {@link GraphicsFactory}.
 *
 * This utility gives quick access to the important semantic
 * parts of an element.
 */
/**
 * Returns the visual part of a diagram element.
 *
 * @param gfx
 *
 * @return
 */
export function getVisual(gfx: SVGElement): SVGElement;
/**
 * Returns the children for a given diagram element.
 *
 * @param gfx
 * @return
 */
export function getChildren(gfx: SVGElement): SVGElement;
