name: MERGE_MASTER_TO_DEVELOP
on:
  push:
    branches:
    - "master"

jobs:
  Create_pull_request:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Create pull request to develop
      uses: repo-sync/pull-request@65194d8015be7624d231796ddee1cd52a5023cb3
      with:
        source_branch: ""                                       # If blank, default: triggered branch
        destination_branch: "develop"                           # If blank, default: master
        pr_title: "Merge master to develop"                     # Title of pull request
        pr_body: "This integrates latest changes from master."  # Full markdown support, requires pr_title to be set
        pr_reviewer: "modeling/modeling-dev"                    # Comma-separated list (no spaces)
        github_token: ${{ secrets.GITHUB_TOKEN }}
